// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package fir_accelerator_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} accelerate_en;
    struct packed {logic q;} coeff_write_en;
    struct packed {logic q;} clr_c;
  } fir_accelerator_reg2hw_control_reg_t;

  typedef struct packed {logic [2:0] q;} fir_accelerator_reg2hw_coeff_addr_reg_t;

  typedef struct packed {logic [31:0] q;} fir_accelerator_reg2hw_coeff_data_reg_t;

  typedef struct packed {logic [31:0] q;} fir_accelerator_reg2hw_sensor_data_reg_t;

  typedef struct packed {logic [31:0] q;} fir_accelerator_reg2hw_result_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } busy;
  } fir_accelerator_hw2reg_control_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } fir_accelerator_hw2reg_result_reg_t;

  typedef struct packed {
    logic d;
    logic de;
  } fir_accelerator_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    fir_accelerator_reg2hw_control_reg_t control;  // [101:99]
    fir_accelerator_reg2hw_coeff_addr_reg_t coeff_addr;  // [98:96]
    fir_accelerator_reg2hw_coeff_data_reg_t coeff_data;  // [95:64]
    fir_accelerator_reg2hw_sensor_data_reg_t sensor_data;  // [63:32]
    fir_accelerator_reg2hw_result_reg_t result;  // [31:0]
  } fir_accelerator_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    fir_accelerator_hw2reg_control_reg_t control;  // [36:35]
    fir_accelerator_hw2reg_result_reg_t  result;   // [34:2]
    fir_accelerator_hw2reg_status_reg_t  status;   // [1:0]
  } fir_accelerator_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_CONTROL_OFFSET = 5'h0;
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_COEFF_ADDR_OFFSET = 5'h4;
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_COEFF_DATA_OFFSET = 5'h8;
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_SENSOR_DATA_OFFSET = 5'hc;
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_RESULT_OFFSET = 5'h10;
  parameter logic [BlockAw-1:0] FIR_ACCELERATOR_STATUS_OFFSET = 5'h14;

  // Register index
  typedef enum int {
    FIR_ACCELERATOR_CONTROL,
    FIR_ACCELERATOR_COEFF_ADDR,
    FIR_ACCELERATOR_COEFF_DATA,
    FIR_ACCELERATOR_SENSOR_DATA,
    FIR_ACCELERATOR_RESULT,
    FIR_ACCELERATOR_STATUS
  } fir_accelerator_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] FIR_ACCELERATOR_PERMIT[6] = '{
      4'b0001,  // index[0] FIR_ACCELERATOR_CONTROL
      4'b0001,  // index[1] FIR_ACCELERATOR_COEFF_ADDR
      4'b1111,  // index[2] FIR_ACCELERATOR_COEFF_DATA
      4'b1111,  // index[3] FIR_ACCELERATOR_SENSOR_DATA
      4'b1111,  // index[4] FIR_ACCELERATOR_RESULT
      4'b0001  // index[5] FIR_ACCELERATOR_STATUS
  };

endpackage

