// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module fir_accelerator_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output fir_accelerator_reg_pkg::fir_accelerator_reg2hw_t reg2hw,  // Write
    input fir_accelerator_reg_pkg::fir_accelerator_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import fir_accelerator_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic control_accelerate_en_qs;
  logic control_accelerate_en_wd;
  logic control_accelerate_en_we;
  logic control_coeff_write_en_qs;
  logic control_coeff_write_en_wd;
  logic control_coeff_write_en_we;
  logic control_clr_c_qs;
  logic control_clr_c_wd;
  logic control_clr_c_we;
  logic control_busy_qs;
  logic [2:0] coeff_addr_qs;
  logic [2:0] coeff_addr_wd;
  logic coeff_addr_we;
  logic [31:0] coeff_data_qs;
  logic [31:0] coeff_data_wd;
  logic coeff_data_we;
  logic [31:0] sensor_data_qs;
  logic [31:0] sensor_data_wd;
  logic sensor_data_we;
  logic [31:0] result_qs;
  logic status_qs;

  // Register instances
  // R[control]: V(False)

  //   F[accelerate_en]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_accelerate_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_accelerate_en_we),
      .wd(control_accelerate_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.accelerate_en.q),

      // to register interface (read)
      .qs(control_accelerate_en_qs)
  );


  //   F[coeff_write_en]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_coeff_write_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_coeff_write_en_we),
      .wd(control_coeff_write_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.coeff_write_en.q),

      // to register interface (read)
      .qs(control_coeff_write_en_qs)
  );


  //   F[clr_c]: 2:2
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_clr_c (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_clr_c_we),
      .wd(control_clr_c_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.clr_c.q),

      // to register interface (read)
      .qs(control_clr_c_qs)
  );


  //   F[busy]: 3:3
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_control_busy (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.control.busy.de),
      .d (hw2reg.control.busy.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(control_busy_qs)
  );


  // R[coeff_addr]: V(False)

  prim_subreg #(
      .DW      (3),
      .SWACCESS("RW"),
      .RESVAL  (3'h0)
  ) u_coeff_addr (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(coeff_addr_we),
      .wd(coeff_addr_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.coeff_addr.q),

      // to register interface (read)
      .qs(coeff_addr_qs)
  );


  // R[coeff_data]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_coeff_data (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(coeff_data_we),
      .wd(coeff_data_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.coeff_data.q),

      // to register interface (read)
      .qs(coeff_data_qs)
  );


  // R[sensor_data]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_sensor_data (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sensor_data_we),
      .wd(sensor_data_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sensor_data.q),

      // to register interface (read)
      .qs(sensor_data_qs)
  );


  // R[result]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_result (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.result.de),
      .d (hw2reg.result.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.result.q),

      // to register interface (read)
      .qs(result_qs)
  );


  // R[status]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.de),
      .d (hw2reg.status.d),

      // to internal hardware
      .qe(),
      .q (),

      // to register interface (read)
      .qs(status_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == FIR_ACCELERATOR_CONTROL_OFFSET);
    addr_hit[1] = (reg_addr == FIR_ACCELERATOR_COEFF_ADDR_OFFSET);
    addr_hit[2] = (reg_addr == FIR_ACCELERATOR_COEFF_DATA_OFFSET);
    addr_hit[3] = (reg_addr == FIR_ACCELERATOR_SENSOR_DATA_OFFSET);
    addr_hit[4] = (reg_addr == FIR_ACCELERATOR_RESULT_OFFSET);
    addr_hit[5] = (reg_addr == FIR_ACCELERATOR_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(FIR_ACCELERATOR_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(FIR_ACCELERATOR_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(FIR_ACCELERATOR_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(FIR_ACCELERATOR_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(FIR_ACCELERATOR_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(FIR_ACCELERATOR_PERMIT[5] & ~reg_be)))));
  end

  assign control_accelerate_en_we = addr_hit[0] & reg_we & !reg_error;
  assign control_accelerate_en_wd = reg_wdata[0];

  assign control_coeff_write_en_we = addr_hit[0] & reg_we & !reg_error;
  assign control_coeff_write_en_wd = reg_wdata[1];

  assign control_clr_c_we = addr_hit[0] & reg_we & !reg_error;
  assign control_clr_c_wd = reg_wdata[2];

  assign coeff_addr_we = addr_hit[1] & reg_we & !reg_error;
  assign coeff_addr_wd = reg_wdata[2:0];

  assign coeff_data_we = addr_hit[2] & reg_we & !reg_error;
  assign coeff_data_wd = reg_wdata[31:0];

  assign sensor_data_we = addr_hit[3] & reg_we & !reg_error;
  assign sensor_data_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = control_accelerate_en_qs;
        reg_rdata_next[1] = control_coeff_write_en_qs;
        reg_rdata_next[2] = control_clr_c_qs;
        reg_rdata_next[3] = control_busy_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[2:0] = coeff_addr_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = coeff_data_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = sensor_data_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = result_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = status_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module fir_accelerator_reg_top_intf #(
    parameter  int AW = 5,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output fir_accelerator_reg_pkg::fir_accelerator_reg2hw_t reg2hw,  // Write
    input fir_accelerator_reg_pkg::fir_accelerator_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  fir_accelerator_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


